profile = "dev"
[server]
addr = "0.0.0.0"
port = 3000

[db]
host = "192.168.1.215"
port = 5432
username = "postgres"
password = "123123"
database_name = "uptop"
max_connections = 5

[sentry]
dsn = ""

[secret]
private_access_key = "static/secret_key/private_access_rsa_key.pem"
public_access_key = "static/secret_key/public_access_rsa_key.pem"
private_refresh_key = "static/secret_key/private_refresh_rsa_key.pem"
public_refresh_key = "static/secret_key/public_refresh_rsa_key.pem"

[redis]
username = "default"
password = "HEeQ5Sx9OlV7SMBImXFT9yIFA7pBNkhO"
host = "192.168.1.215"
port = 6379
database_name = "0"
